---
title: "gorilla_analysis"
author: "Lana"
date: '2023-04-04'
output: html_document
---

```{r}
dir_path = "../gorilla_data/2025/data_exp_88447-v25/"

```

list all data files
```{r}
# dir_path = paste(base_path, sub_folder, sep="")

dir_list = list.files(path = dir_path)
files_list = c()

for (dir in dir_list){
  final_dir_path = paste(dir_path, dir, sep="")
  # temp_list = list.files(path = final_dir_path)
  # files_list = c(files_list, paste(final_dir_path, temp_list, sep="/"))
  files_list = c(files_list, final_dir_path)
}

print(files_list)
# remove different ones
```

Give up whole analysis, just look at strength

```{r}
file_path = files_list[1]
df = read.csv(file_path, stringsAsFactors=F)

strength = gsub('0: no motion', '0', df[-1,33])
strength = gsub('5: a strong motion', '5', strength)

illusion_name = df[-1,27]

results = data.frame(illusion_name, strength)

# plot(results$strength)

```


```{r}
for (file_path in files_list[-1]){
  df = read.csv(file_path, stringsAsFactors=F)
  
  # todo use not n
  if(df[2,27] != "Bot Checks: Visual Search" 
     & df[2,27] != "Instructional Manipulation"
     & df[2,27] != "Consent"
     & df[2,27] != "Experiment Description"
     & df[2,27] != "Instructions"
     ){
    
    strength = gsub('0: no motion', '0', df[-1,33])
    strength = gsub('5: a strong motion', '5', strength)
    
    illusion_name = df[-1,27]
    temp = data.frame(illusion_name, strength)
    results = rbind(results, temp)
  }

}

# remove empty rows
results = results[!apply(results == "", 1, all),]
```


```{r}
# assign id to illusion
ids <- data.frame(unique(results$illusion_name), c(1:length(unique(results$illusion_name))))
colnames(ids) = c("illusion_name", "illusion_id")

results$illusion_id <- ids$illusion_id[match(results$illusion_name, ids$illusion_name)]

# plot(results$illusion_id, results$strength, xaxt="n")
# axis(side = 1, at = 1:length(ids$illusion_id), labels = ids$illusion_name)
```

```{r}

averages = c()
for (id in unique(ids$illusion_id)){
  sub = subset(results, illusion_id == id)
  averages = c(averages, mean(as.numeric(sub$strength)))
}

ill_ave = data.frame(unique(ids$illusion_id), unique(ids$illusion_name), averages)
colnames(ill_ave) = c("id", "name", "mean_strength")

```

```{r}
plot(ill_ave$id, ill_ave$mean_strength, xaxt="n", ylim = c(0, 5), xlab = "Illusion", ylab = "Strength")
axis(side = 1, at = 1:length(ill_ave$name), labels = ill_ave$name)
```

Read data from EIGen own evaluation

```{r}
file_path = "../gorilla_data/2025/eigen_own_ratings.csv"
own_ratings = read.csv(file_path, stringsAsFactors=F)
all_ratings = merge(ill_ave, own_ratings[,c("gorilla_name","score")], by.x='name', by.y='gorilla_name')

all_ratings = all_ratings[order(all_ratings$id), ]
```


```{r}
plot(all_ratings$id, all_ratings$mean_strength/5, 
     ylim = c(0,1), type = "l", col = "blue", xaxt="n", 
     xlab = "Illusion", ylab = "Strength")
points(all_ratings$id, all_ratings$score, type = "l", col = "red")
axis(side = 1, at = 1:length(all_ratings$name), labels = all_ratings$name)

```


Read comments

```{r}
file_path = files_list[15]
df = read.csv(file_path, stringsAsFactors=F)
# 
# strength = gsub('0: no motion', '0', df[-1,32])
# strength = gsub('5: a strong motion', '5', strength)
# 
# illusion_name = df[-1,27]
# 
# type_results = data.frame(illusion_name, strength)

comments_results = c()

for (file_path in files_list){
  df = read.csv(file_path, stringsAsFactors=F)
  
  # todo use not n
  if(df[2,27] != "Bot Checks: Visual Search" 
     & df[2,27] != "Instructional Manipulation"
     & df[2,27] != "Consent"
     & df[2,27] != "Experiment Description"
     & df[2,27] != "Instructions"
     ){
    
    comments = df[-1,32]
    comments = comments[nzchar(comments)]
    comments_results = c(comments_results, comments)
  }

}


comments_results
```


----

Paste without NA
useless

```{r}
paste5 <- function(..., sep = " ", collapse = NULL, na.rm = F) {
  if (na.rm == F)
    paste(..., sep = sep, collapse = collapse)
  else
    if (na.rm == T) {
      paste.na <- function(x, sep) {
        x <- gsub("^\\s+|\\s+$", "", x)
        ret <- paste(x[!is.na(x) & !(x %in% "")], collapse = sep)
        is.na(ret) <- ret == ""
        return(ret)
      }
      df <- data.frame(..., stringsAsFactors = F)
      ret <- apply(df, 1, FUN = function(x) paste.na(x, sep))

      if (is.null(collapse))
        ret
      else {
        paste.na(ret, sep = collapse)
      }
    }
}
```

Read all files

```{r}

result_columns = c("participant_id", "task", "illusion", "motion_type", "strength")
results = data.frame(matrix(nrow = 0, ncol = length(result_columns))) 
colnames(results) = result_columns
value_true = 1

motion_type_cols = c()
  
for (file_path in files_list){
  df = read.csv(file_path, stringsAsFactors=F)
  
  if (length(motion_type_cols)==0){
    for (col in colnames(df)){
      if (grepl("motion.type.object.4", col, fixed = TRUE)){
        motion_type_cols = c(motion_type_cols, col)
      }
    }
  }
  
  # merge motion columns but skip header
  df['motion_type'] = paste(df[motion_type_cols][-1,])

  # data has different formats
  columns = colnames(df)
  if("illusory.motion" %in% columns){
    sub = df[c("Participant.Private.ID", "Task.Name", "illusory.motion.quantised", "motion_type", "response.1.1.quantised")]
    sub$illusory.motion.quantised = c(df["illusory.motion.quantised"] == value_true)
    colnames(sub) = result_columns

    sub = subset(sub, task!="")
    # TODO deal with 3rd format issue here
    if (length(sub[,1])>0 & sub[1,1]!=""){
      results = rbind(results, sub)
    }
    
  } 
}

colnames(results) = result_columns
print(results)

tasks = unique(results$task)
for (t in tasks){
  sub = subset(results, task==t)
  print(sub)
}
```

```{r}
print(results)

# average strength for each task
columns = c("illusion", "strength") 
ratings = data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(ratings) = columns

for (t in unique(results$task)){
  sub = subset(results, task==t)
  strength = mean(sub$strength)
  ratings = rbind(ratings, c(t, strength))
}

colnames(ratings) = columns
print(ratings[order(ratings$strength, decreasing=TRUE),])

# plot each participant

for (p in unique(results$participant_id)){
  sub = subset(results, participant_id==p)
  plot(sub$strength, xaxt = "n", xlab = "")
  axis(1, at = c(1: length(sub$task)),
     labels = sub$task, las = 2
     )
}

```


