---
title: "gorilla_analysis"
author: "Lana"
date: '2023-04-04'
output: html_document
---

```{r}
dir_path = "gorilla_data/"

```

list all data files
```{r}
dir_list = list.files(path = dir_path)
files_list = c()

for (dir in dir_list){
  final_dir_path = paste(dir_path, dir, sep="")
  temp_list = list.files(path = final_dir_path)
  files_list = c(files_list, paste(final_dir_path, temp_list, sep="/"))
}

```


Find correct number of columns
```{r}
file_path = files_list[2]
df = read.csv(file_path, stringsAsFactors=F)
columns = colnames(df)

df[,27:39]
```

```{r}
# for illusion tasks
selected_columns_ids = c(27, 30, 33, 35, 36, 37, 38)
df[c(1,2),selected_columns_ids]

# for attention checks

```


Read all files

```{r}

result_columns = c("task", "response")
results = data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(results) = result_columns
  
for (file_path in files_list){
  df = read.csv(file_path, stringsAsFactors=F)

  # data has different formats
  columns = colnames(df)
  if("illusory.motion" %in% columns){
    # print(df[c("Task.Name", "illusory.motion")])
    sub = df[c("Task.Name", "illusory.motion")]
    colnames(sub) = result_columns
    sub = subset(sub, task!="")
    # TODO deal with 3rd format issue here
    if (length(sub[,1])>0 & sub[1,1]!=""){
      results = rbind(results, sub)
    }
    
  } else if("Response" %in% columns){
    sub = subset(df, Question.Key=="illusory-motion")
    sub = sub[c("Task.Name", "Response")]
    colnames(sub) = result_columns
    sub = subset(sub, task!="")
    # TODO deal with 3rd format issue here
    if (length(sub[,1])>0 & sub[1,1]!=""){
      results = rbind(results, sub)
    }
  }
  # dirty ignore errors
  # tryCatch({
  #   print(df[c("Task.Version", "Task.Name", "illusory.motion")])
  # }, error=function(e){
  #   print(df)
  #   # df[c("Question.Key", "Response")]
  #   })
}

print(results)

tasks = unique(results$task)
for (t in tasks){
  sub = subset(results, task==t)
  print(sub)
}
```

